name: HardcoreCycle
main: dev.wibbleh.the_cycle.Main
version: 1.0.0
api-version: 1.21
commands:
  cycle:
    description: Manage and trigger hardcore world cycles
    usage: /cycle setcycle <n> | /cycle cycle-now | /cycle status
    permission: thecycle.cycle
    permission-message: You do not have permission to use that command.

permissions:
  thecycle.cycle:
    description: Allows running /cycle and forwarding cycle requests from lobby to hardcore
    default: op

channels:
  # Declare plugin messaging channels used by this plugin. Some server/proxy environments
  # prefer channels be declared in plugin.yml in addition to runtime registration.
  - BungeeCord
  - thecycle:rpc
